config/routes.rb
Rails.application.routes.draw do

  resources :shops, only: [:index, :show]
  resources :items, only: [:index]

end

app/models/item.rb
class Item < ActiveRecord::Base

  def get_discount(item)
    value = item[:price] * (80)
    value.to_f/100
  end
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end


end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

  def index
    @shops = Shop.all
  end

  def show
    @total = 0
    @items = Shop.find(params[:id]).items
    @items.each do |item|
      @total += item.price
    end
    @total = 2.5
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/index.html.erb
<h1>Items Index</h1>


<% @items.each do |item| %>
<%= link_to item.name, items_path %>
<%= item.price %>
<%= item.description %>
<%= item.get_discount(item) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CandyShop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shops/index.html.erb
<h1>Shops Index</h1>

<% @shops.each do |shop| %>
<li> <%= link_to shop.name, shop_path(shop) %> </li>
<% end %>

app/views/shops/show.html.erb
<h1>Items In Shop</h1>

<h3> Potential revenue: <%= @total %> </h3>

<% @items.each do |item|  %>
<%= item.name %>
<%= item.price %>
<% end %>